project:
  type: website
  output-dir: docs
  render: 
  - "*.qmd"
  - "!materials/"

website: 
  page-navigation: true
  title: "Go fastR: High Performance Computing with R" 
  site-url: https://luwidmer.github.io/fastR-website/
  repo-url: https://github.com/luwidmer/fastR-website
  repo-actions: [edit, issue]
  repo-branch: master
  
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by the [ARDM Workshop](https://joanacmbarros.github.io/ardm-website/)."
    
  sidebar:
    logo: "img/logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://luwidmer.github.io/fastR-website/
        text: "fastR Course Website"
      - icon: github
        href: https://github.com/luwidmer/fastR-website
        text: "fastR Course GitHub Repository"
  
    style: "docked"
    search: true
    collapse-level: 3
    border: true
    
    contents:
      - file: index.qmd
        text: "Welcome"
      - file: agenda.qmd
        text: "Agenda"
      - href: materials.qmd
        text: "Materials"
      - href: further-links.qmd
        text: "Further links"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


